POST http://localhost:5000/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImlkIjoiNjRlNmY1ODQxYzViYjVlZjcyNWQ0MWY3IiwiaWF0IjoxNjkyODU4MDAzLCJleHAiOjE2OTI4NjE2MDN9.TXq3jcxxEI6vtSvIXMzBteHJ3IIE7jzOwrdw75v6e4s

{
  "title": "Test title 2",
  "author": "Test author 2",
  "url": "Test url 2",
  "user": "64e6f5841c5bb5ef725d41f7"
}